name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Composer and Yarn dependencies
        run: |
          yarn install -g yarn --ignore-scripts

      - name: Build assets
        run: yarn build

      - name: Create deployment archive
        run: zip -r deployment.zip . -x 'node_modules/*' 'var/*' 'vendor/*'

      - name: Upload to server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          remote_path: ${{ secrets.PATH }}
          server: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          password: ${{ secrets.PASSWORD }}
          sftpArgs: -r
          port: ${{ secrets.PORT }}
          local_path: deployment.zip
