name: CI/CD for symfony 6 App

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Yarn
        run: npm install -g yarn --ignore-scripts

      - name: Install dependencies
        run: yarn install

      - name: Build and deploy
        run: |
          yarn build
      
      - name: Install zip
        run: sudo apt-get -y install zip

      - name: Create deployment archive
        run: zip -r deployment.zip . -x 'node_modules/*' 'var/*' 'vendor/*'

      - name: Upload to server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          remote_path: ${{ secrets.PATH }}
          server: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          password: ${{ secrets.PASSWORD }}
          sftpArgs: -r
          port: ${{ secrets.PORT }}
          local_path: deployment.zip